version: '3'

services:
  app:
    build: .
    container_name: prismaapi-app
    ports:
      - "3333:3333"
      - "5555:5555"
    command: npm run start:dev
    env_file:
      - .env
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: prismaapi-db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=prismaapi
